services:
  - type: web
    name: swasthaai
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py

    envVars:
      - key: PORT
        value: 10000
